### ISSUE TITLE
'form_tag' misses 'do' 

### ISSUE THREAD

**Issue by ShunYaoCodes** [learn-co-curriculum/delete-forms-rails#10]
This block of code will raise a syntax error:

![image](https://user-images.githubusercontent.com/33703565/39527534-a6adcc26-4def-11e8-9ea3-ceb9195e819b.png)

should add a do to form_tag:

<%= form_tag people_path(@person.id), method: "delete"  do %>

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
