### ISSUE TITLE
This lesson is really unclear

### ISSUE THREAD

**Issue by atxrenegade** [learn-co-curriculum/delete-forms-rails#11]
I enjoyed the style and voice it was written in but the technical material was not clearly delivered.  It's not clear what the relationship between the third and fourth code samples are in the "Ignorance is Bliss section", and the only frame of reference is the single word "enhance".

**Comment by jenmyers** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
