### ISSUE TITLE
On the learn.co website, the 'buttons_to' section is not being displayed

### ISSUE THREAD

**Issue by DBuckley0126** [learn-co-curriculum/delete-forms-rails#13]

**Comment by Sdcrouse** [comment]
I see what you mean. The top of the README mentions `button_to`, but it's not discussed anywhere in the document.

**Comment by kierblk** [comment]
Came here to submit and issue for this very issue. Attaching screenshots to better explain this problem.

Screenshot of the lesson on Learn.co, scrolled all the way to the bottom. The content ends with the Fancy JavaScript Helper section.
 
<img width="624" alt="Screen Shot 2020-01-20 at 10 31 07 PM" src="https://user-images.githubusercontent.com/49502059/72773374-ed62c480-3bd4-11ea-8db9-d5bdc20cfa27.png">

Screenshot of the readme on Learn's GitHub repo for the lesson. Scrolled all the way to the bottom showing that the `button_to` section is visible.

<img width="623" alt="Screen Shot 2020-01-20 at 10 32 49 PM" src="https://user-images.githubusercontent.com/49502059/72773389-f2277880-3bd4-11ea-9293-85d5eec0fc70.png">

Inspecting on Learn.co does not show the `button_to` section either. However, the `button_to` section is a `##` heading, while the other visible sections are all `#` headings. Possible cause? 

Steps to reproduce:
1. Visit Learn.co `Delete Forms` lesson via a web browser.
2. Scroll to the bottom and visually verify `button_to` section is missing.

Steps to correct:
1. Possibly switch the heading to a `#` as other sections with a `#` heading are visible.
2. ?

Issue present utilizing both Chrome and Firefox browsers.

**Comment by rrcobb** [comment]
Merged #14 to attempt to address. If it's still a problem, reopen this issue or open a new one, and we'll check it out!

**Comment by Sdcrouse** [comment]
I think that works! I can see the **Use `button_to`** section in the lesson now.
