### ISSUE TITLE
Misplaced lesson?

### ISSUE THREAD

**Issue by rnbronstein** [learn-co-curriculum/delete-forms-rails#5]
The Readme suggests that readers do not yet know how to update in Rails, leading me to believe that this lesson was intended to go in the preceding CRUD unit. If this is the correct placement for the lesson, perhaps the Readme might explain the connection between #destroy and Validations, or there could be a note in the CRUD section to let students know that they'll be learning how to delete later.

**Comment by gj** [comment]
temp-fixed: https://github.com/learn-co-curriculum/delete-forms-rails/pull/6

Lesson still might be out of place, but I at least made it aware that we already know all about `UPDATE` at this point in the curriculum.

**Comment by cjbrock** [comment]
Hi @rnbronstein! Thank you for your feedback on the curriculum. We're currently looking at our Rails section as a whole, and will definitely take this into account while we are doing so. Thank you for taking your time to make Learn a better place for other students. 

<3 // Corinna
