### ISSUE TITLE
Issue in "Ignorance is bliss" section

### ISSUE THREAD

**Issue by markdegroat** [learn-co-curriculum/delete-forms-rails#7]
Lines 5-7 in the first snippet of this section are as follows:
<%= form_tag people_path(@person.id), method: "delete" %>
  <%= submit_tag "Delete #{@person.name}" %>
<% end %>

The end tag here will actually break this form_tag setup do to there not being a "do", and I believe you want to actually to pointing the form to "person_path(@person.id)".  
This code will send a delete request to "/people.[id]" but we want it to send it to "/people/[id]".

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
