### ISSUE TITLE
form_tag should have a "do"

### ISSUE THREAD

**Issue by jrgreiner115** [learn-co-curriculum/delete-forms-rails#9]
Hi, this example in the Delete forms lab, the <%= form_tag %> should have a do at the end
source: https://stackoverflow.com/questions/27478508/syntax-error-unexpected-keyword-ensure-expecting-end-of-input-with-rails

original: 
```
<h2><%= @person.name %></h2>
<%= @person.email %>
<%= form_tag people_path(@person.id), method: "delete" %>
  <%= submit_tag "Delete #{@person.name}" %>
<% end %>

```
updated:
```
<h2><%= @person.name %></h2>
<%= @person.email %>
<%= form_tag people_path(@person.id), method: "delete" do %>
  <%= submit_tag "Delete #{@person.name}" %>
<% end %>
```

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
